name: Daily Blacklist Update

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  build:
    name: Daily Blacklist Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Update Custom
        run: python update.py --custom

      - name: Update Lists Gambling
        run: python update.py -m --gambling

      - name: Update Lists Privacy
        run: python update.py -m --privacy

      - name: Update Lists ADBlock
        run: python update.py -m --adblock

      - name: Commit and push
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: '[Scheduled] Update Blacklists'
